{
  stdenv,
  lib,
  fetchFromGitHub,
  gnat,
  gprbuild,
  ansi-ada
}:

stdenv.mkDerivation {
  pname = "progress-indicators";
  version = "0.0.2";

  src = fetchFromGitHub {
    owner = "pyjarrett";
    repo = "progress_indicators";
    rev = "61ad049bb6e203ed84575c2ad52e17b32bdbba77";
    hash = "sha256-ToeI/eSKdexDrLUxVTZjaib3j5RewEz+wLHklebDIPw=";
  };

  nativeBuildInputs = [
    gnat
    gprbuild
  ];
  buildInputs = [ ansi-ada ];

  # This configuration is from config/progress_indicators_config.gpr
  # when building `progress_indicators` with `alr build`.
  configurePhase = ''
    mkdir -p config
    cat > config/progress_indicators_config.gpr << 'EOF'
    --  Configuration for progress_indicators generated by Alire
    with "ansiada.gpr";
    abstract project Progress_Indicators_Config is
      Crate_Version := "0.0.2";
      Crate_Name := "progress_indicators";

      Alire_Host_OS := "linux";

      Alire_Host_Arch := "x86_64";

      Alire_Host_Distro := "distribution_unknown";
      Ada_Compiler_Switches := External_As_List ("ADAFLAGS", " ");
      Ada_Compiler_Switches := Ada_Compiler_Switches &
              (
                "-Og" -- Optimize for debug
              ,"-ffunction-sections" -- Separate ELF section for each function
              ,"-fdata-sections" -- Separate ELF section for each variable
              ,"-g" -- Generate debug info
              ,"-gnatwa" -- Enable all warnings
              ,"-gnatw.X" -- Disable warnings for No_Exception_Propagation
              ,"-gnatVa" -- All validity checks
              ,"-gnatW8" -- UTF-8 encoding for wide characters
              );

      type Build_Profile_Kind is ("release", "validation", "development");
      Build_Profile : Build_Profile_Kind := "development";

    end Progress_Indicators_Config;

    EOF
  '';

  buildPhase = ''
    runHook preBuild
    gprbuild -p progress_indicators.gpr
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    gprinstall -P progress_indicators.gpr --prefix=$out \
      --no-manifest \
      --mode=dev \
      -p
    runHook postInstall
  '';

  meta = {
    description = "Iterator-based directory walks.";
    homepage = "https://github.com/pyjarrett/dir_iterators";
    maintainers = [ lib.maintainers.candreano ];
    license = lib.licenses.asl20;

    # TODO: is this actually true
    platforms = lib.platforms.all;
  };
}
