{
  stdenv,
  lib,
  fetchFromGitHub,
  gnat,
  gprbuild,
}:

stdenv.mkDerivation {
  pname = "trendy_terminal";
  version = "0.0.7";

  src = fetchFromGitHub {
    owner = "pyjarrett";
    repo = "trendy_terminal";
    rev = "730526e3498fb1c09b6a300be0d91b4ba478fe8d";
    hash = "sha256-4981YlwAiRZEjDoxiT4zqwap5Ey73V38TDVAEdDZpjg=";
  };

  nativeBuildInputs = [
    gnat
    gprbuild
  ];

  # This configuration is from config/trendy_terminal_config.gpr
  # when building `trendy_terminal` with `alr build`.
  configurePhase = ''
    mkdir -p config
    cat > config/trendy_terminal_config.gpr << 'EOF'
    --  Configuration for trendy_terminal generated by Alire
    abstract project Trendy_Terminal_Config is
      Crate_Version := "0.0.7";
      Crate_Name := "trendy_terminal";

      Alire_Host_OS := "linux";

      Alire_Host_Arch := "x86_64";

      Alire_Host_Distro := "distribution_unknown";
      Ada_Compiler_Switches := External_As_List ("ADAFLAGS", " ");
      Ada_Compiler_Switches := Ada_Compiler_Switches &
              (
                "-Og" -- Optimize for debug
              ,"-ffunction-sections" -- Separate ELF section for each function
              ,"-fdata-sections" -- Separate ELF section for each variable
              ,"-g" -- Generate debug info
              ,"-gnatwa" -- Enable all warnings
              ,"-gnatw.X" -- Disable warnings for No_Exception_Propagation
              ,"-gnatVa" -- All validity checks
              ,"-gnatW8" -- UTF-8 encoding for wide characters
              );

      type Build_Profile_Kind is ("release", "validation", "development");
      Build_Profile : Build_Profile_Kind := "development";

    end Trendy_Terminal_Config;

    EOF
  '';

  buildPhase = ''
    runHook preBuild
    gprbuild -p trendy_terminal.gpr
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    gprinstall -P trendy_terminal.gpr --prefix=$out \
      --no-manifest \
      --mode=dev \
      -p
    runHook postInstall
  '';

  meta = {
    description = "A Windows/Linux library for enabling terminal settings, such as echo and line input.";
    homepage = "https://github.com/pyjarrett/trendy_terminal";
    maintainers = [ lib.maintainers.candreano ];
    license = lib.licenses.asl20;

    # TODO: is this actually true
    platforms = lib.platforms.all;
  };
}
