{
  stdenv,
  lib,
  fetchFromGitHub,
  gnat,
  gprbuild,
}:

stdenv.mkDerivation {
  pname = "ansiada";
  version = "1.1.0";

  src = fetchFromGitHub {
    owner = "mosteo";
    repo = "ansi-ada";
    rev = "v1.1.0";
    hash = "sha256-h3SMp5p5LFut5fmLjXjt3i+Jqxn9H7P1s/kzYlpciYk=";
  };

  nativeBuildInputs = [
    gnat
    gprbuild
  ];

  # This configuration is from config/ansiada_config.gpr
  # when building `ansiada` with `alr build`.
  configurePhase = ''
    mkdir -p config
    cat > config/ansiada_config.gpr << 'EOF'
    --  Configuration for ansiada generated by Alire
    abstract project Ansiada_Config is
      Crate_Version := "1.1.0";
      Crate_Name := "ansiada";

      Alire_Host_OS := "linux";

      Alire_Host_Arch := "x86_64";

      Alire_Host_Distro := "distribution_unknown";
      Ada_Compiler_Switches := External_As_List ("ADAFLAGS", " ");
      Ada_Compiler_Switches := Ada_Compiler_Switches &
              (
                "-Og" -- Optimize for debug
              ,"-ffunction-sections" -- Separate ELF section for each function
              ,"-fdata-sections" -- Separate ELF section for each variable
              ,"-g" -- Generate debug info
              ,"-gnatwa" -- Enable all warnings
              ,"-gnatw.X" -- Disable warnings for No_Exception_Propagation
              ,"-gnatVa" -- All validity checks
              ,"-gnaty3" -- Specify indentation level of 3
              ,"-gnatya" -- Check attribute casing
              ,"-gnatyA" -- Use of array index numbers in array attributes
              ,"-gnatyB" -- Check Boolean operators
              ,"-gnatyb" -- Blanks not allowed at statement end
              ,"-gnatyc" -- Check comments
              ,"-gnaty-d" -- Disable check no DOS line terminators present
              ,"-gnatye" -- Check end/exit labels
              ,"-gnatyf" -- No form feeds or vertical tabs
              ,"-gnatyh" -- No horizontal tabs
              ,"-gnatyi" -- Check if-then layout
              ,"-gnatyI" -- check mode IN keywords
              ,"-gnatyk" -- Check keyword casing
              ,"-gnatyl" -- Check layout
              ,"-gnatym" -- Check maximum line length
              ,"-gnatyn" -- Check casing of entities in Standard
              ,"-gnatyO" -- Check that overriding subprograms are explicitly marked as such
              ,"-gnatyp" -- Check pragma casing
              ,"-gnatyr" -- Check identifier references casing
              ,"-gnatyS" -- Check no statements after THEN/ELSE
              ,"-gnatyt" -- Check token spacing
              ,"-gnatyu" -- Check unnecessary blank lines
              ,"-gnatyx" -- Check extra parentheses
              ,"-gnatW8" -- UTF-8 encoding for wide characters
              );

      type Build_Profile_Kind is ("release", "validation", "development");
      Build_Profile : Build_Profile_Kind := "development";

    end Ansiada_Config;

    EOF
  '';

  buildPhase = ''
    runHook preBuild
    gprbuild -p ansiada.gpr
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall
    gprinstall -P ansiada.gpr --prefix=$out \
      --no-manifest \
      --mode=dev \
      -p
    runHook postInstall
  '';

  meta = {
    description = "ANSI control sequences for the Ada language.";
    homepage = "https://github.com/mosteo/ansi-ada";
    maintainers = [ lib.maintainers.candreano ];
    license = lib.licenses.mit;

    # TODO: is this actually true
    platforms = lib.platforms.all;
  };
}
